#ifndef CARMA_CORBA_TEST_HELLO_IDL
#define CARMA_CORBA_TEST_HELLO_IDL

module carma {
module corba {
module test {

    const string HELLO_NAME = "carma.corba.test.Hello";

    interface Hello {

        void hi();

    }; // interface Hello

};};}; // module carma::corba::test
#endif
