/** LOGGER	-  receive messages from logit sub			*/
/*: misc								*/
/*+
	PROGRAM LOGGER
	LOGGER manages a message queue with log messages
	generated by subroutine logit.  The messages are
	time stamped and written to files $HATLOG/log.date. New
	log files are opened for each day.
	(be sure that the kernel has sys V messages 
	configured)
									*/
/*-- 5jul94 fix spurious error mess  wh					*/
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/msg.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <stdlib.h>
#include <errno.h>

int messout(char *) ;

main ()
{
  key_t key = 111 ;
  int queid ;
  int yes, st ;
  struct msgbuf  *mbuffer, *mfirst ;
  struct msqid_ds *dummy ;
  int nbytes = 70;
  long mtype = 1 ;
  int flags = MSG_NOERROR ;
  int mlength ;

/*  --	open the message stream   */
	queid = msgget(key,IPC_CREAT|0666) ;
	if (queid < 0 ) {
	   perror("Log queue msgget fails:") ;
	   return -1 ;
	}
	yes = msgctl(queid,IPC_RMID,dummy) ;
	if (yes == -1 ) {
	  perror("Log queue cleanup fails:") ;
	  return -1 ;
	}
	queid = msgget(key,IPC_CREAT|0666) ;
	if (queid == -1 ) {
	  perror("Log queue creation fails:") ;
	  return -1 ;
	}
/*  --	fix up message buffers  */
	mbuffer = (struct msgbuf *)malloc((unsigned)(sizeof(struct msgbuf) -
		sizeof(mbuffer->mtext) + nbytes )) ;
	mfirst = (struct msgbuf *)malloc((unsigned)(sizeof(struct msgbuf) -
		sizeof(mfirst->mtext) + nbytes )) ;

/*  --	write first message into message queue to check  */
	strcpy(mfirst->mtext,"LOGGER is restarted") ;
	mfirst->mtype = 1 ;
	st = msgsnd(queid,mfirst,strlen(mfirst->mtext),0) ;
	if (st == -1 ) perror("LOG: startup message fails:") ;

/*  --	receive messages and write them loop   */
	for (;;) {
	  mlength = msgrcv(queid,mbuffer,nbytes,mtype,flags) ;
	  if (mlength > 0) {
		mbuffer->mtext[mlength] = NULL ;
		yes = messout((char *)mbuffer->mtext) ;
		if (yes < 0) return -1 ;
	  }
	  else if (errno != 0) perror("LOG: msgrcv error:") ;
	}
}
/*  MESSOUT	- write out log message to file				*/
/*: logger								*/
/*+
	char *messout(text of message) ;
   
	messout receives the messages from logger and formats them
	with a timestamp and carriage return them writes them into
	the appropriate file log.date.  The file is opened for each
	line.

  ARGUMENTS:
  TEXT(char ,input)	Message text (no timestamp or CR)
	sep 91  wh
	sep 93 wh  add log. to filename					*/
/*--									*/

int messout(char *text)
{
  char stamp[14] ;
  char line [140] ;
  char filename[14] ;
  char path[60] ;
  char *ng ;
  time_t tp ;
  struct tm *tim ;
  FILE *file ;
  int n ;

/*  --	generate the time-stamp and path name */
	tp = time(NULL) ;
	tim = gmtime(&tp) ;
	n = strftime(stamp,13,"%d%h %R|\0",tim) ;
	n = strftime(filename,13,".%d%h%y\0",tim) ;
	filename[3] = (char)tolower((int)filename[3]) ;
	ng = getenv("HATLOG") ;
	if (ng == NULL) {
		perror("LOG: no HATLOG:") ;
		return -1 ;
	}
	strcpy(path,ng) ;
	strcat(path,"/log") ;
	strcat(path,filename) ;

/*  --	open-write-close the file  */
	file = fopen(path,"a") ;
	if (file == NULL) {
		perror("LOG: can't open logfile: ") ;
		return -1 ;
	}
	fprintf(file,"%s%s\n",stamp,text) ;
	fclose(file) ;
	return 0 ;
}			
